username:
password:
phone_number:

positions:
- Data Scientist
- # Another position you want to search for
- # A third position you want to search for

locations:
- Remote
- # A second location you want to search in 

# --------- Optional Parameters -------
uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo

output_filename: # PATH TO OUTPUT FILE (default output.csv)

black_list_companies:
- # Company names you want to ignore

black_list_titles:
- # Add job titles you want to ignore

job_list_filter_keys:
- Most Recent # Most Recent | Most Relevant - Sort by
- Any Time # Any Time | Past Month | Past Week | Past 24 hours - Date posted
- Fast Apply # Fast Apply | Usual Apply - work only with fast apply or get the full job list